on: 
 push:
   branches: [ master ]
name: Build
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v2
      with:
        name: Openboard
        path: ./app/build/outputs/apk/debug/app-debug.apk 
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Openboard Debug Apk
        document: ./app/build/outputs/apk/debug/app-debug.apk
